### ISSUE TITLE
Flask app

### ISSUE THREAD

**Issue by Kvm99** [sphericalpm/Eriwan#1]

**Comment by AndreyAnokhin** [comment]
The flask app structure bases on ["The Flask Mega-Tutorial"](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world) (but without blueprints).

**Comment by Kvm99** [comment]
отлично


>Суббота, 17 августа 2019, 12:51 +03:00 от Andrey Anokhin <notifications@github.com>:
>
>The flask app structure bases on  "The Flask Mega-Tutorial" before using blueprints.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Мария Кузнецова
